import Head from "next/head";
import { useCallback } from "react";
import styles from "../styles/Home.module.css";
import { IDKitWidget, ISuccessResult } from "@worldcoin/idkit";

export default function Home() {
	const handleProof = useCallback(
		() => (result: ISuccessResult) => {
			console.log(result);
		},
		[]
	);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh" }}>
				<IDKitWidget actionId="get_this_from_the_dev_portal" onSuccess={handleProof}>
					{({ open }) => <button onClick={open}>Click me</button>}
				</IDKitWidget>
			</div>
		</div>
	);
}
