import Head from "next/head";
import dynamic from "next/dynamic";
import "@worldcoin/idkit/build/index.css";
import styles from "../styles/Home.module.css";

const IDKitNoSSR = dynamic(() => import("@worldcoin/idkit").then((mod) => mod.IDKitWidget), {
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh" }}>
        <IDKitNoSSR />
      </div>
    </div>
  );
}
