name: CI

on:
    push:
        branches: ['main']
    pull_request:

jobs:
    build:
        name: Lint & Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: 8

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  cache: 'pnpm'
                  node-version: 18

            - name: Install dependencies
              run: pnpm install

            - name: Typecheck & Build
              run: pnpm build

            # NOTE: Lint needs to run after build because it checks the compiled files for types
            - name: Lint
              run: pnpm lint

            - name: Typecheck idkit-core
              run: cd packages/core && pnpm tsc

            - name: Typecheck idkit
              run: cd packages/react && pnpm tsc

            - name: Typecheck idkit-standalone
              run: cd packages/standalone && pnpm tsc
