name: CI

on:
    push:
        branches: ['main']
    pull_request:

jobs:
    build:
        name: Lint, Typecheck & Test Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.12.2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  cache: 'pnpm'
                  node-version: 18

            - name: Install dependencies
              run: pnpm install

            - name: Typecheck & Build
              run: pnpm build

            # NOTE: Lint needs to run after build because it checks the compiled files for types
            - name: Lint
              run: pnpm lint

            - name: Typecheck examples/with-next
              run: cd examples/with-next && pnpm tsc

    standalone-test:
        name: Test idkit-standalone in browser
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.12.2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  cache: 'pnpm'
                  node-version: 18

            - name: Install dependencies
              run: pnpm install

            - name: Typecheck & Build
              run: pnpm build

            - name: Install Chrome
              run: |
                  cd packages/standalone
                  pnpm install-chrome

            - name: Serve /build files
              run: |
                  cd packages/standalone
                  http-server ./build/ -p 8080 &

            - name: Serve /build files
              run: |
                  cd packages/standalone
                  pnpm test:browser
